# Generated by Django 4.2.7 on 2023-11-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='channel_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField()),
                ('message_id', models.IntegerField()),
            ],
            options={
                'db_table': 'channel_content',
            },
        ),
        migrations.CreateModel(
            name='group_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.TextField(blank=True, null=True)),
                ('channel_text', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.DateTimeField()),
                ('message_details', models.CharField(max_length=100)),
                ('message_id', models.IntegerField()),
                ('replied_message_details', models.CharField(max_length=100)),
                ('replied_message_id', models.IntegerField()),
                ('joined', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('url', 'url_type'), ('file', 'file_type'), ('video', 'video_type'), ('photo', 'photo_type'), ('audio', 'audio_type'), ('text', 'text_type')], default='text', max_length=10)),
                ('parser_channel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.channel_content')),
            ],
            options={
                'db_table': 'group_content',
            },
        ),
    ]
